### PR TITLE
Update public.py

### PR DESCRIPTION
**Pull request by jellelangen**
Fix for allow_feedback_message_on_positive functionality

### CODE REVIEW

**Comment by Nigel2392** [comment]
Whoops! Thank you for the PR. :)

I'll create a pre-release right away, planning some updates for this package in the near future.

**Comment by jellelangen** [comment]
Thank you for accepting so quickly! We kind of need it tomorrow, so this is perfect :)

**Comment by Nigel2392** [comment]
> Thank you for accepting so quickly! We kind of need it tomorrow, so this is perfect :)

Available in tag "v1.3.3a1" as opposed to RC1. Hope you don't mind!

**Comment by jellelangen** [comment]
No problem, thanks again! We figured and we've got it installed and working!

**Pull request merged**
